---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
  ignore_errors: yes
- name: checking for logstash installation in {{ logstash_install_dir }}
  become: yes
  stat:
    path: '{{ logstash_install_dir }}'
  changed_when: false
  register: logstash_binary_dir
- when: not logstash_binary_dir.stat.exists
  block:
    - name: downloading {{ logstash_tgz_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ logstash_tgz_url }}'
        dest: '{{ logstash_tmp_tgz }}'
        checksum: '{{ logstash_checksum }}'
        mode: 0644
    - name: unarchiving to {{ logstash_parent_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ logstash_tmp_tgz }}'
        dest: '{{ logstash_parent_install_dir }}'
        creates: '{{ logstash_install_dir }}'
  always:
    - name: cleanup {{ logstash_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ logstash_tmp_tgz }}'
        state: absent

- name: linking {{ logstash_link_dir }} to {{ logstash_install_dir }}
  become: yes
  become_user: root
  file:
    src: '{{ logstash_install_dir }}'
    dest: '{{ logstash_link_dir }}'
    state: link

- name: adding to default path...
  become: yes
  become_user: root
  with_items:
    - f: logstash.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
