---
logstash_ver: 7.12.1
logstash_mirror: https://artifacts.elastic.co/downloads/logstash
logstash_os: linux
logstash_arch: x86_64
logstash_parent_install_dir: /usr/local

logstash_checksums:
  '7.10.1':
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.10.1-linux-x86_64.tar.gz.sha512
    linux-x86_64: sha512:78b488a915d03d23a96badbd04a01c88be13cd7aee5c0ba300595a4a5bb5be9caf48d2f9ec1085a3a7937e83e6db15040192197fbe7367a6df93840ac7971021
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.10.1-darwin-x86_64.tar.gz.sha512
    darwin-x86_64: sha512:ce8962a473da38248d530b75f6b106c5d69235993c6bec9da1d0d412ce6eaa9d9522f6a4ff63b27e6c589a672d215d85258b8ec10d56681e64bd51172e100669
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.10.1-windows-x86_64.zip.sha512
    windows-x86_64: sha512:9cfb0f034615c04e2d0f7f33c330a7130de24d9d8ffb4208d9616689b7624d964893fde1893e5a75319aac1942265c855573d7aa28cfd226bdc72dffba98a63f
  '7.10.2':
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.10.2-linux-x86_64.tar.gz.sha512
    linux-x86_64: sha512:34099b34a05c6b85b1b355310bd190b606aa0bcce1cad07bf5fd98959e54f61860bdd697cca8f3cdab2d2b815bbc2a788d2e14dcac4b3d85a0d5bafd72d2b170
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.10.2-darwin-x86_64.tar.gz.sha512
    darwin-x86_64: sha512:9e7ff014aedf2788057d3e86daf3b3c50be6f74a2f795cfd95f1b2b16226555a2654a39bbd4cb88f9eb54b8b68d13673907458518946ee7f46d31e4f6495e6ff
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.10.2-windows-x86_64.zip.sha512
    windows-x86_64: sha512:0ff392a933b29706dc9d9ccb98dff87a5fb7a9630dacb95c3f24de7ef290e56684cac330581579baae2e66b53d3aeea1cebd70d89bbcedcb8ff9cf34930ab0c0
  '7.11.0':
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.11.0-linux-x86_64.tar.gz.sha512
    linux-x86_64: sha512:ecebfc4c7f47fd93e2915e85028d6f8d0d17c4993cf71048343ba0f3bf2e3be757bddb9715413fc3395fd6b56ccddadbf617df27f3c7c7ca1db22304fa4969f3
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.11.0-darwin-x86_64.tar.gz.sha512
    darwin-x86_64: sha512:37b663dcc7f92a9d65e59fd7b618adb22860ebe533317a565d850b4a8bc3f7a6ff4ac2572b534a43caff7aafb4244e55ee538d682dcd11f882e7882fb7351f70
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.11.0-windows-x86_64.zip.sha512
    windows-x86_64: sha512:45a71c65bbe752147df8ea331a362152374fc5156e467cd8b6f657ba5498f9aab3eadee1de7b45a997ea71974ba5f0fe9e96eaa9e864926408499fe74fd15895
  '7.11.2':
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.11.2-linux-x86_64.tar.gz.sha512
    linux-x86_64: sha512:a1a62fe82db5965f955aa3fd08a6927e539c07eee4e02831fab7c4e79965453826140abe1c3458691ba8f221a818103aa10475816e336b98b4ecf08593a7f5e9
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.11.2-darwin-x86_64.tar.gz.sha512
    darwin-x86_64: sha512:3217e823fa0cbcc82581e8d0b6fbf84b4b571451d017439d8bca969811a2d16173d532f7674287451c08f34da6343dd2082458c6d22ff119ac96259590b1ca36
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.11.2-windows-x86_64.zip.sha512
    windows-x86_64: sha512:9074c569350009f89121faade038e28393d6a46d31fd506fb5a73ed1b2c195632d3bebdfb900dcc6717a45e476883e404d55e3fdaeb35d7059eeffaf83488b8d
  '7.12.1':
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.12.1-linux-x86_64.tar.gz.sha512
    linux-x86_64: sha512:9ef32dbeb4269d904a775a1cf5833b09cc5b8b71c03f953641fd5de5c27ba51ec878d9e74cdd98255d37fcd39d592deea72832bdce26cbb2827db4ae3b294834
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.12.1-darwin-x86_64.tar.gz.sha512
    darwin-x86_64: sha512:f7f12bdfa815c51c981b23ebfee224c6bc2047a347f3de7ce38a7d9f1b26a5e77b05bbaffc8cf947c2845af81069e430bfa9ab11757c369371a4c78845c6b51f
    # https://artifacts.elastic.co/downloads/logstash/logstash-7.12.1-windows-x86_64.zip.sha512
    windows-x86_64: sha512:a3635808e0d945ccec876c2f8db9deae23b71adfebca9d6912c7e57794a158413e7e26ebe250cd356b2fdcfdc93b6b76762e21250524fa245e188e852f92cda0
