dependencies:
- role: bash-completion #aams.bash
  #version: v1.1.7
- role: aams.unarchive-deps
  version: v1.2.0
galaxy_info:
  author: Andrew Rothstein
  company: BlackRock
  description: logstash
  galaxy_tags:
  - logaggregation
  license:
  - MIT
  min_ansible_version: 2.0
  platforms:
  - name: Archlinux
    versions:
    - all
  - name: Debian
    versions:
    - bullseye
    - buster
    - stretch
  - name: EL
    versions:
    - 7
    - 8
  - name: Fedora
    versions:
    - 31
    - 32
  - name: Ubuntu
    versions:
    - bionic
    - focal
    - xenial
