---
galaxy_info:
  author: Andrew Rothstein
  description: installs bash
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: Debian
      versions:
        - bullseye
        - buster
        - stretch
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 31
        - 32
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
  galaxy_tags:
    - development

dependencies: []
